[project]
name = "cuptir"
channels = ["nvidia", "conda-forge"]
platforms = ["linux-64"]

[system-requirements]
cuda = "12.9"

[dependencies]
cuda-cudart-dev = "12.9.*"
cuda-cupti-dev = "12.9.*"
cuda-nvrtc = "12.9.*"
rust = "*"
