name: Rust

on:
  pull_request:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - cuda-12080
          - cuda-12090
          - cuda-13000

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: "true"
      - uses: dtolnay/rust-toolchain@1.88
        id: rust-toolchain
        with:
          components: clippy
      - name: Check
        run: cargo check -v --workspace --all-targets --exclude cudarc --features ${{ matrix.version }},serde
      - name: Clippy
        run: cargo clippy -v --workspace --all-targets --exclude cudarc --features ${{ matrix.version }},serde
